# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Restaurant'),
            preserve_default=False,
        ),
    ]
