# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_staffmember_restaurant'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='in_store',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=12),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='subtype',
            field=models.CharField(default='default', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(default='default', max_length=60),
            preserve_default=False,
        ),
    ]
