# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-18 00:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(
                    choices=[('OPEN', 'Open'), ('ORDERED', 'Ordered'), ('IN_PROGRESS', 'In progress'),
                             ('COMPLETE', 'Complete'), ('RELEASED', 'Released')], default='Open', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
