# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-19 13:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0001_initial'),
        ('orders', '0002_orderelement_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='organizations.StaffMember'),
            preserve_default=False,
        ),
    ]
