# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-26 14:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0002_auto_20200123_0044'),
        ('orders', '0004_auto_20200119_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='inventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory'),
            preserve_default=False,
        ),
    ]
