# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0005_orderelement_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='product',
            field=models.CharField(default='default_product', max_length=60),
            preserve_default=False,
        ),
    ]
