# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0006_orderelement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderelement',
            name='in_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderelement',
            name='offer_number_in_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderelement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
